name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install dependencies
      - run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi

      # Setup Python for MCP server
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Install uv for Python dependencies
      - run: pip install uv

      # Set TEST_MODE for CI
      - run: echo "TEST_MODE=true" >> $GITHUB_ENV

      # Run basic tests
      - run: |
          # Test Nx workspace
          npx nx --version
          npx nx show projects
          
          # Test MCP server can be installed
          cd apps/mcp/cli_use
          uv venv --allow-existing
          uv pip install --editable .
          
          # Quick test that server can start
          timeout 5s uv run cli_use_server start --transport sse --port 9000 || true